### ISSUE TITLE
Speed Limiter

### ISSUE THREAD

**Issue by jbalat** [OpenSource-EBike-firmware/TongSheng_TSDZ2_motor_controller_firmware#14]
Speed Limit can be set on LCD but does not appear to save

Motor code does not support the speed limiter yet.
 Request a taper off rather than hard cutoff.  Eg speed limit 25, starts to reduce at 26 and drops back to zero at 28

**Comment by casainho** [comment]
My priority is not the speed limiter but other more difficult things to implement.

Yes, I also think that power should decrease slowly as we approach the speed limit -- this is also the feedback I have from users on the KT firmware. But I think the speed limit value configure on LCD should be the value after power assist is 0, at least I think that is the expectation from users. You can always put a higher speed limit if you prefer for it to cut after the limit.

**Comment by ncvanleeuwen** [comment]
I've started working on the speed limiter as I need this function as well. Later on I want to implement the road/offroad mode as well, there should be something implemented on the LCD already if I'm correct?

**Comment by jbalat** [comment]
On my Trek it tapers of very quickly at 25 then no assistance at 27. It is so painful hitting the limiter.

**Comment by ncvanleeuwen** [comment]
I'm thinking of doing it more or less the same way. I think this is how it works on most standard e-bikes. If hitting the limiter at a certain speed is too painful, just simply increase the limiter 😃

**Comment by ncvanleeuwen** [comment]
@casainho is the current wheel speed (ui16_wheel_speed_x10 ) calculated and multiplied by 10 so I have to divide it by 10 to get the real speed km/h?

`void calc_wheel_speed (void)
{
  // calc wheel speed in km/h
  if (ui16_wheel_speed_sensor_pwm_cycles_ticks < WHEEL_SPEED_SENSOR_MIN_PWM_CYCLE_TICKS)
  {
    f_wheel_speed_x10 = ((float) PWM_CYCLES_SECOND) / ((float) ui16_wheel_speed_sensor_pwm_cycles_ticks); // rps
    f_wheel_speed_x10 *= configuration_variables.ui16_wheel_perimeter; // millimeters per second
    f_wheel_speed_x10 *= 0.036; // ((3600 / (1000 * 1000)) * 10) kms per hour * 10
    ui16_wheel_speed_x10 = (uint16_t) f_wheel_speed_x10;
  }
  else
  {
    ui16_wheel_speed_x10 = 0;
  }
}
`

**Comment by casainho** [comment]
Yes, as that value is used on LCD3 as xx.x km/h.

It also may be good for you to get higher resolution than only 1km/h.

**Comment by ncvanleeuwen** [comment]
Thanks for your valuable feedback!

**Comment by casainho** [comment]
Post  by Dirkro » Mon Aug 27, 2018

Hi, 
maybe the speed limit can be installed:

all in km/h , it is a (hopefuly) similar to the behavior of Bosch & Yamaha :
The factor is 1 0.5km/h under "speedlimit" and goes down to 0 linear until two km/h over the speed limit. Then the factor is =0 

Sorry, but the only thing i can programm is Basic...

speed_limit_factor=0.4*((speedlimit+2)-speed) 
if speed<(speed_limit-0.5) then speed_limit_factor=1
if speed >(speed_limit+2) then speed_limit_factor=0 

output power= temp_power*speed_limit_factor

**Comment by casainho** [comment]
If I understand correctly, we can implement a linear ramp that decreases the motor power to zero. We need to defined the speed at which is 0 (speed_limit + 1??) and the speed it starts decreasing.

See that the already existing bicycle wheel speed variable is x10, meaning we have decimal resolution, so we can work with for instance (speed_limit + 1.5).

**Comment by ncvanleeuwen** [comment]
See my commit: https://github.com/ncvanleeuwen/TongSheng_TSDZ2_motor_controller_firmware/commit/cb78c1ae4c85748b78fcd3a6405c040041ffea72

**Comment by endlesscadence** [comment]
I've closed the pull request.

**Comment by endlesscadence** [comment]
Pull request closed.

**Comment by casainho** [comment]
Speed limit was implemented on last release. Also the issue of resetting to 25km/h, was a code on LCD3 that was there to always reset to 25km/h because of off road mode -- I commented the code for now and the issue is solved.

eeprom_write_if_values_changed() is commented because seems it takes to much time to run and causes issues with the motor control...
