### ISSUE TITLE
Lights control

### ISSUE THREAD

**Issue by casainho** [OpenSource-EBike-firmware/TongSheng_TSDZ2_motor_controller_firmware#3]

**Comment by wheex1** [comment]
I flashed the light branch to the controller, and it's not working don't switch the lights.

**Comment by troebi2** [comment]
Lights control is a major feature. Isn't it possible to adapt the code from the stock firmware?

**Comment by casainho** [comment]
> Isn't it possible to adapt the code from the stock firmware?
If someone manage to look at original dissasembled firmware and find what is need to be done, I can implement.

**Comment by wheex1** [comment]
Lights control is now working in 0.9 but can't turn it off after the back-light is enabled on the lcd, the only way to turn of the lights is to turn off the entire controller.

**Comment by casainho** [comment]
Fixed on "development" branch.
