### ISSUE TITLE
Offroad mode

### ISSUE THREAD

**Issue by endlesscadence** [OpenSource-EBike-firmware/TongSheng_TSDZ2_motor_controller_firmware#31]
We could add the offroad mode fairly easily now we have the speed limiter. We should discuss the most intuitive and fast way for enabling/disabling the offroad mode.

Controls:

- Disabled on power on (default/configurable)
- Enabled by buttons (to be discussed).
- Disabled by buttons (to be discussed).

A long press on up/down (or multiple presses?) could work and is easy but might collide with the walk assist functionality. Or are offroad mode and walk assist mutually exclusive?

Configuration menu options:

1. Offroad functionality enabled/disabled. This also enables the controls or not.
2. Enabled on system startup. Default disabled.
3. Custom speed limit. Enabled/disabled. When disabled use the other speed limit.
4. Custom speed limit in km/h.
5. Power limit. Enabled/disabled. (do we need this? Or should we just hide the power on the display?)
6. Power limit in W. (do we need this? Or should we just hide the power on the display?)

Speed limiter and offroad mode:

- Motor is limited by the speed limiter, regardless whether offroad mode is configured.
- When offroad mode is off (but enabled) and a custom speed limit (in offroad configuration) is configuration, use that speed limit.

Not sure whether we need the custom speed limit in offroad mode configuration. Do we need power limiting? What about feedback on the LCD display if the offroad mode is on or off?

**Comment by casainho** [comment]
A lot of options.... not so easy to understand and discuss.

About user understanding when it is limited (no off road mode), maybe keep "assist" symbol (on top of assist number) on and on off road mode, blink the "assist" symbol.

**Comment by endlesscadence** [comment]
I'm working on this one. I'm not doing any power limiting for now. I think standard ebikes aren't limited to 250W peak power too. But I'm open for ideas! We can also hide the power on the display (or clamp it to 250W). @casainho thanks for the blinking assist symbol idea (not walk assist)! Works well!

One issue I have with the controls:
I'm using the power + up/down buttons to turn on/off offroad mode but this collides with the "power limiting?" feature. For now I've made it mutually exclusive: when offroad mode is enabled (in configuration) no power limiting is available. Any better ideas?

@BartLoos 
I understand that "When offroad mode is off (but enabled)" is confusing. Let me explain:
- We can configure the offroad mode functionality, we can enable it or disable in the configuration menu.
- If enabled in the configuration menu, the user can turn it on or off using quick access buttons.

So on/off means: currently active or not. Enabled/disabled means: the feature is (un)usable.

**Comment by casainho** [comment]
I think on limited mode it should also limit the power, at least as I understand, on EU it is:
1. limit of 250W
2. limit of 25km/h
3. can't work with throttle over 6km/h (this means can also have walk assist)

Maybe you can put options on LCD for each value of limit mode (1 and 2), so users can configure a different value. And default values can be the 250 and 25.

**Comment by endlesscadence** [comment]
Thanks. I will do that. Configuration value 2. is already implemented. 

Regarding the throttle: in some EU countries it's not even allowed to mount a throttle I think. Walk assist is allowed though. 

I'm not sure if we should limit the power to 250W. If I'm correct this power by law is the nominal power not the peak power. But if it's configurable then it's up to the user.

**Comment by Dirkkro** [comment]
Please don't limit the power! 
Those who want it can limit the Amps to maybe 8 (36V) this will fulfill the the requirements. I think we don't need to limit our engine much more than Bosch or Yamaha are doing

**Comment by BartLoos** [comment]
@endlesscadence 
Thanks for explaining "When offroad mode is off (but enabled)" now it is clear for me.

for power limiting in the EU: 
Before 2018 it was 25km/u,  walkassist  6 km/u, continuous 250 watt and max peak power <1000w. 
Since 1 januari they only speak over 250w not about the peak power anymore.

But it is of course difficult to determine if the bike is of 2017 or 2018.
In NL you can have a throttle but only for the walk assist.

**Comment by endlesscadence** [comment]
Thanks a lot guys for your valuable input! I've just tested the feature and it's working great except for the power limiting which isn't correctly used yet but can be configured already. 

We have the following configuration options:
1. Offroad functionality -> enable/disable, default disabled
2. Offroad mode (unlimited speed) active on system startup -> enable/disable, default disabled
3. Speed limit when offroad mode not active but enabled (setting 1) -> km/h, default 25 km/h
4. Power limit -> enable/disable, default disabled
5. Power limit -> watts, default 250W

When setting 1 is enabled the following applies:
1. Offroad mode is shown by the motor assist symbol (directly above the assist level)
    - No blinking -> offroad mode inactive
    - Blinking -> offroad mode active
2. Button on/off + button up -> offroad mode active
3. Button on/off + button down -> offroad mode inactive

**Comment by endlesscadence** [comment]
@Dirkkro @BartLoos 
Feature is almost ready now. Are you able to test and confirm that it is working for you? I think I fixed the (optional) power limiter as well. 

Hex files here:
[KT_LCD3_Flexible_OpenSource_firmware-v0.11_offroad_beta.hex](https://github.com/endlesscadence/TongSheng_TSDZ2_motor_controller_firmware/raw/offroad_mode/TSDZ2_and_KT_LCD3_Flexible_OpenSource_firmwares/KT_LCD3_Flexible_OpenSource_firmware-v0.11_offroad_beta.hex)
[TSDZ2_Flexible_OpenSource_firmware-v0.11_offroad_beta.hex](https://github.com/endlesscadence/TongSheng_TSDZ2_motor_controller_firmware/raw/offroad_mode/TSDZ2_and_KT_LCD3_Flexible_OpenSource_firmwares/TSDZ2_Flexible_OpenSource_firmware-v0.11_offroad_beta.hex)

**Comment by BartLoos** [comment]
Hallo Nico,

Ik ben bezig om offroad feature te testen maar heb wat problemen met het
configureren na het flashen van de lcd scherm.

Er zijn nu 9 menu's terwijl we op wiki er 7 staan dus weet nu niet precies
wat wat doet.
Daarnaast heb ik in in menu 1 "Battery voltage and current setup" al een
mismatch in de submenu's op de wiki staan er 3 en ik heb nu 4 submenu's.

Weet jij zo waar ik de juiste submenu's kan raadplegen want weet nu niet
wat ik aan het configureren ben ;-)

Groete,

Bart.



Op za 15 sep. 2018 om 22:11 schreef endlesscadence <notifications@github.com

**Comment by endlesscadence** [comment]
Hi @BartLoos I think your comment was deleted because only english language is accepted here. To answer your questions:

Yes, the wiki information isn't completely correct for the firmware you're testing. That's because that firmware is still in beta.

Regarding menu 1: Looking at the code the following is correct (for beta version only!):
0 - battery max current
1 - battery low voltage cut off
2 - battery cells number
3 - battery pack resistance (don't know how this works)

See menu 7 and information above for offroad mode configuration, I would clear the data memory and ignore other menu's (maybe except menu 0) and leave them default for now.

**Comment by BartLoos** [comment]
Thanks for the info!

**Comment by endlesscadence** [comment]
@BartLoos @Dirkkro I've just tested the power limiting, seems to work well now but I didn't do a real test ride. Please let me know what you think about it! I think offroad mode is ready now.

**Comment by BartLoos** [comment]
I am just back from a test drive, everything for the offroad was working very well!! Good work EndlessCadence.

I had some trouble maybe due to the fact I didn't clear the data memory. Can someone explain me how to do that exactly?

**Comment by endlesscadence** [comment]
@BartLoos Thanks for your feedback!! Data memory can easily be cleared by writing two zeros (00) to the first position at address 00004000 using ST Visual Programmer, this should be at the top of the data memory tab. Then the firmware will write all defaults to the data memory again.

**Comment by endlesscadence** [comment]
Implemented
