### ISSUE TITLE
Lights cannot be turned off

### ISSUE THREAD

**Issue by endlesscadence** [OpenSource-EBike-firmware/TongSheng_TSDZ2_motor_controller_firmware#33]
Once turned on they cannot be turned off. The display indicator shows they're off, but they're not.

**Comment by endlesscadence** [comment]
Seems to be a display issue. I've created a PR there https://github.com/OpenSource-EBike-firmware/Kunteng_LCD3_firmware/pull/6

**Comment by casainho** [comment]
Solved.
