### ISSUE TITLE
Enable throttle setting

### ISSUE THREAD

**Issue by pjlegend** [OpenSource-EBike-firmware/TongSheng_TSDZ2_motor_controller_firmware#36]
(using V.11) I am getting current to the throttle but can you change the read only setting on config screen 7.2 so it can be enabled. Throttle is not working at the moment. Cheers, Paddy

**Comment by casainho** [comment]
Sorry, I could not understand.
1. Throttle does no work?
2. What do you want to say about the settings on config screens?

**Comment by pjlegend** [comment]
Thanks for your work and response Casainho.

1. Yes, throttle does not work
2.is it possible to have an option to enable and disable throttle?

**Comment by casainho** [comment]
2. Yes, if the motor temperature sensor is enabled, throttle should not work!! Please see if you have that option enabled.

Can you see on the configurations the value of throttle ADC changing when you change throttle position??

**Comment by pjlegend** [comment]
Yes, motor temp sensing is disabled

Throttle adc value is changing when I change possition:

 46 when open
187 when full throttle

**Comment by casainho** [comment]
Can you also please ser the values of human power adn duty-cycle??

The issue is that now I can't connect a trhottle to my ebike so I can't test.

**Comment by pjlegend** [comment]
Values are 0 for both.

**Comment by endlesscadence** [comment]
I don't have a throttle because a version with the throttle wasn't readily available at that time and it's not allowed here. So unfortunately I can't help.

**Comment by pjlegend** [comment]
Bummer, I will have to go without until its fixed in a future update. Wish I had the skills to work on it myself. Also, Im happy to donate a controller if anyone needs it for development. Cheers

**Comment by endlesscadence** [comment]
@pjlegend I think I've found the issue why it isn't working. Can you try to turn the pedals and applying throttle together? Please do this at various speeds and circumstances. I'm willing to create some experimental builds for you to test, no problem.

**Comment by pjlegend** [comment]
@endlesscadence Thanks mate, it's working perfect now in various configurations. The throttle lag is better than it was on the stock firmware as well which is a massive plus. I will keep testing to see if any issues arise and update but for now it's great!
