### ISSUE TITLE
README points ot documentation for previous project

### ISSUE THREAD

**Issue by spth** [OpenSource-EBike-firmware/TongSheng_TSDZ2_motor_controller_firmware#5]
The README points to https://opensourceebikefirmware.bitbucket.io/, which states "THIS CODE IS NOT BEING DEVELOPED NOR MANTAINED ANYMORE.", and "Casainho started to use the same base code developed for KT motor controllers firmware, on the TSDZ2 motor controllers -- see here: https://github.com/OpenSource-EBike-firmware/TongSheng_TSDZ2_motor_controller_firmware", which points back here.

So when looking for the documentation for the latest version of whatever Casainho wrote, one gets stuck in a loop.

Philipp

**Comment by casainho** [comment]
Corrected. Thanks.
